---
version: 2.0.2
slug: stremio
name: stremio
description: Stremio server with fixes
url: https://github.com/dedins/hassio-addons/tree/main/stremio
webui: "http://[HOST]:[PORT:11470]"
codenotary: notary@home-assistant.io
map: 
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  11470/tcp: 11470
  13470/tcp: null
ports_description:
  11470/tcp: stremio http port
  13470/tcp: stremio https port
startup: system
