---
version: 1.0.1
slug: certbottana
name: certbottana
description: certbottana
url: https://github.com/dedins/hassio-addons/tree/main/certbottana
codenotary: notary@home-assistant.io
advanced: true
map: 
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: false
options:
  work_dir: /share/certbottana/
  domains: []
  url: http://remote-public-php-server.com
  username: admin
  password: admin
schema:
  work_dir: str
  domains: str
  url: str
  username: str
  password: str
startup: system
