---
version: 1.0.0
slug: gitea
name: gitea
description: gitea
url: https://github.com/dedins/hassio-addons/tree/main/gitea
codenotary: notary@home-assistant.io
advanced: true
map: 
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: false
ports:
  3000/tcp: 3000/tcp
  2222/tcp: 2222/tcp
ports_description:
  3000/tcp: web
  2222/tcp: ssh
privileged:
  - NET_ADMIN
options:
  gitea_work_dir: /share/gitea/
schema:
  gitea_work_dir: str
startup: system
