---
version: 1.0.0
slug: serge
name: serge
description: serge
url: https://github.com/dedins/hassio-addons/tree/main/serge
webui: "http://[HOST]:[PORT:8008]"
codenotary: notary@home-assistant.io
map: 
  - share:rw
  - usr:rw
  - data:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8008/tcp: 8008
ports_description:
  8008/tcp: serge port
startup: system
