---
version: 1.0.4
slug: bigagi
name: bigagi
description: bigagi
url: https://github.com/dedins/hassio-addons/tree/main/bigagi
webui: "http://[HOST]:[PORT:3000]"
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: bigagi port
startup: system
init: false