---
version: 1.0.1
slug: bigAGI
name: bigAGI
description: obsidian web running on linux docker
url: https://github.com/dedins/hassio-addons/tree/main/bigAGI
webui: "http://[HOST]:[PORT:3001]"
codenotary: notary@home-assistant.io
init: false
map:
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: bigAGI http port
startup: system
