---
version: 1.0.0
slug: big
name: big
description: big
url: https://github.com/dedins/hassio-addons/tree/main/big
webui: "http://[HOST]:[PORT:3000]"
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: big port
startup: system
