---
version: 1.0.3
slug: bigAGI
name: bigAGI
description: big-AGI web running on linux docker
url: https://github.com/dedins/hassio-addons/tree/main/big-AGI
webui: "http://[HOST]:[PORT:8080]"
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: bigAGI http port
startup: system
