---
version: 2.0.0
slug: anisette
name: anisette
description: anisette
url: https://github.com/dedins/hassio-addons/tree/main/anisette
webui: "http://[HOST]:[PORT:6969]"
codenotary: notary@home-assistant.io
map: 
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  6969/tcp: 6969
ports_description:
  6969/tcp: anisette port
startup: system
