---
version: 1.0.8
slug: blobsaver
name: blobsaver
description: blobsaver
url: https://github.com/dedins/hassio-addons/tree/main/blobsaver
codenotary: notary@home-assistant.io
advanced: true
map: 
  - share:rw
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: false
options:
  save_path: /share/blobs/${DeviceIdentifier}/${MajorVersion}/${FullVersionString}
  include_betas: true
  devices:
    - name: iPhoneX
      device_id: iPhone14,2
      ecid: 835FF290227123R
      generator: "0x00000000000"
      apnonce: ee1ec7092ee1ec7092ee1
      enabled: true
schema:
  save_path: str
  include_betas: bool
  devices:
    - name: str
      device_id: str
      ecid: str
      generator: str
      apnonce: str
      enabled: bool
startup: system
